apiVersion: v2
name: todo-app
description: An umbrella Helm chart for the complete Todo App
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: todo-frontend
    version: 0.1.0
    condition: todo-frontend.enabled
    alias: frontend
  - name: todo-backend
    version: 0.1.0
    condition: todo-backend.enabled
    alias: backend
  - name: todo-postgres
    version: 0.1.0
    condition: todo-postgres.enabled
    alias: postgres