apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-postgres.fullname" . }}-secrets
  labels:
    {{- include "todo-postgres.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}