apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-postgres.fullname" . }}-svc
  labels:
    {{- include "todo-postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "todo-postgres.selectorLabels" . | nindent 4 }}